# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14e7a57d9374560cefe8b1ce1d750382e5b718b47e4bf8bcc22635697e9e68814a667d10b707af8700235d00150d88623cfe9c9fd7d7cadc2ecd2d65d7a6941a

test:
  secret_key_base: 1273d8bb868fa8294bd5ef83170c88cfc985540e6f56c03c59be350d67c96f53b9b3cb911e0c4584295713f47ff11e3e95ed22918b80e657f44dcb54f73984ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
